"""Generate `qaoa_sampling_legacy.py`: the CURRENT trainer with ONLY the stopping rule reverted.

Why this exists. 18 records in the M0=0 sweep (M* arm, p=3, the ones imported from
`_span_expanded`) carry no circuit_params, because `run_span_expanded.py`'s `rec` dict never
included `best_pars` -- the trainer returned them and the recording script dropped them. Dataset A
needs those parameters to be compilable to hardware.

Re-running them under today's code does NOT reproduce them: `_span_expanded` ran 2026-09-17 14:28 to
09-18 00:12, before the stopping-rule fix, so those circuits were trained under the OLD rule. Three
of the first fifteen re-runs landed on visibly different local optima (worst: n=9 v=142, AR
0.8139 -> 0.6596). To reproduce the ARs that are actually on the plot, the ORIGINAL rule is needed.

The old rule, from d4c89267:code/qaoa/qaoa_sampling_oneshot.py:

    cost_history.append(float(cost_val))        # the OSCILLATING cost, not the monotone best
    if len(cost_history) > 1:
        diff_10 = np.abs(cost_history[-2] - cost_history[-1])
        if diff_10 < epsilon:                   # one adjacent pair; `patience` never consulted
            break

Everything else in the runner is byte-identical between the two versions (verified: the
best_gammas/best_betas/best_cost tracking, the optimiser, epsilon = tolerance_opt, step_check = 10).
So reverting this one block -- rather than checking out the whole old file -- keeps every other
Sep-17-era behaviour while still returning circuit_params and QUBO, which the old recording script
discarded but the trainer always produced.

The live `qaoa_sampling_oneshot.py` is NOT modified. Everything new keeps using the fixed rule.
"""

import hashlib
import os

SRC = "qaoa_sampling_oneshot.py"
DST = "qaoa_sampling_legacy.py"

NEW_BLOCK = '''        if (step + 1) % step_check == 0:
            cost_history.append(float(best_cost))
            if verbose:
                print(f"  step {step+1:>4d}/{steps}  |  cost = {cost_val:+.6f}  "
                      f"|  best = {best_cost:+.6f}")
            if len(cost_history) > patience:
                improvement = cost_history[-(patience + 1)] - cost_history[-1]
                if improvement < epsilon:
                    print(f"...breaking at iteration {step} out of {steps} "
                          f"(best cost improved by {improvement:.3e} < {epsilon:.1e} over the "
                          f"last {patience * step_check} steps)")
                    break
'''

OLD_BLOCK = '''        if (step + 1) % step_check == 0:
            cost_history.append(float(cost_val))
            if verbose:
                print(f"  step {step+1:>4d}/{steps}  |  cost = {cost_val:+.6f}")
            if len(cost_history) > 1:
                diff_10 = np.abs(cost_history[-2] - cost_history[-1])
                if diff_10 < epsilon:
                    print(f"...breaking at iteration {step} out of {steps}")
                    break
'''

src = open(SRC).read()
n = src.count(NEW_BLOCK)
assert n == 1, f"expected exactly 1 ma-QAOA stopping block, found {n} -- refusing to guess"

out = src.replace(NEW_BLOCK, OLD_BLOCK)
banner = (f'"""AUTO-GENERATED by make_legacy_module.py from {SRC} -- DO NOT EDIT.\n\n'
          f'Identical to {SRC} except the ma-QAOA stopping rule, which is reverted to the\n'
          f'pre-fix adjacent-difference test so that runs predating 2026-09-18 can be reproduced\n'
          f'exactly. Use ONLY for reproducing historical results; all new work uses {SRC}.\n"""\n')
out = banner + out

open(DST, "w").write(out)
print(f"wrote {DST}")
print(f"  src sha1 {hashlib.sha1(src.encode()).hexdigest()[:12]}   "
      f"dst sha1 {hashlib.sha1(out.encode()).hexdigest()[:12]}")
print(f"  reverted 1 stopping block; {len(out.splitlines())} lines")
print(f"  {SRC} untouched (mtime {os.path.getmtime(SRC):.0f})")
